#!/bin/bash

# Localize these.
INSPECT_DIR=/var/spool/filter
SENDMAIL=/usr/sbin/sendmail
LOG=/var/log/altermime.log

DISCLAIMER_ADDRESSES=/etc/postfix/disclaimer_addresses

# Exit codes from <sysexits.h>
EX_TEMPFAIL=75
EX_UNAVAILABLE=69

# Clean up when done or when aborting.
trap "rm -f in.$$" 0 1 2 3 15

cd $INSPECT_DIR || { echo $INSPECT_DIR does not exist; exit $EX_TEMPFAIL; }

cat >in.$$ || { echo Cannot save mail to file; exit $EX_TEMPFAIL; }
cp -f in.$$ /tmp/email.txt

# Start processing.
echo "Altermail starting" >> $LOG
date >> $LOG
echo "PWD: " $(pwd) >> $LOG
echo "--- email to process ---" >> $LOG
cat in.$$ >> $LOG
echo "--- email to process ---" >> $LOG

####### Changed From Original Script #######
# obtain From address
from_address=`grep -m 1 "From: " in.$$ | cut -d "<" -f 2 | cut -d ">" -f 1 | gawk '{print $NF}'`
echo "From Address: " ${from_address} >> $LOG

#if [ `grep -wi ^${from_address}$ ${DISCLAIMER_ADDRESSES}` ]; then
if [ `grep -wi ${from_address} ${DISCLAIMER_ADDRESSES}` ]; then
  echo "Matched from address; processing" >> $LOG
  /usr/bin/altermime --input=in.$$ \
                   --disclaimer=/etc/postfix/disclaimer.txt \
                   --disclaimer-html=/etc/postfix/disclaimer.txt \
                   --xheader="X-Copyrighted-Material: Please visit http://www.company.com/privacy.htm" || \
                    { echo Message content rejected; exit $EX_UNAVAILABLE; }
fi
####### Changed From Original Script END #######

echo "--- email after altermime ---" >> $LOG
cat in.$$ >> $LOG
echo "--- email after altermime ---" >> $LOG

$SENDMAIL "$@" <in.$$

rc=$?
echo "Exit code: " ${rc} >> $LOG

#exit $?
exit ${rc}

