#!/bin/bash

killall -q polybar

#polybar mybar 2>&1 | tee -a /tmp/polybar.log & disown
# https://github.com/polybar/polybar/issues/763#issuecomment-331604987
if type "xrandr"
then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1)
	do
		MONITOR=$m polybar --reload mybar &
	done
else
	polybar --reload mybar &
fi

echo "Polybar launched..."


